version: '3'

services:

  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    labels:
      kompose.service.type: nodeport
    volumes:
      - './redis/redis_data/:/bitnami/redis/data'
    restart: always
  
  dashboard:
      build: dashboard/.
      depends_on:
      - redis
      ports:
      - "9181:9181"
      restart: always

  player:
    build: player/.
    depends_on:
      - redis
    devices:
      - "/dev/tty0:/dev/tty0"
      - "/dev/vchiq:/dev/vchiq"
      - "/dev/tty2:/dev/tty2"
      - "/dev/fb0:/dev/fb0"
    volumes:
      - ./player/code/:/app/code/

    restart: always

  telegram:
    build: telegram/.
    depends_on:
      - player
    volumes:
      - ./telegram/code/:/app/code/
    
    environment:
      TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}
      TELEGRAM_PROXY: ${TELEGRAM_PROXY}
    
    restart: always

volumes:
  redis_data:
    driver: local